parameters:
  - name: feedName
    default: ''
  - name: projectPath
    default: ''
  - name: testProjectPath
    default: ''
  - name: dotnetVersion
    default: '9.x'

stages:
  - stage: Build
    displayName: 'Build/Publish'
    jobs:
      - job: Build_And_Publish
        steps:
          - checkout: appRepo
          - task: UseDotNet@2
            displayName: 'Init'
            inputs:
              version: ${{ parameters.dotnetVersion }}

          - task: DotNetCoreCLI@2
            displayName: 'Restore packages'
            inputs:
              command: 'restore'
              projects: ${{ parameters.projectPath }}
              feedsToUse: 'select'
              vstsFeed: ${{ parameters.feedName }}

          - task: DotNetCoreCLI@2
            displayName: 'Build Library'
            inputs:
              command: 'build'
              projects: ${{ parameters.projectPath }}
              arguments: '-c Release --no-restore'

          - task: DotNetCoreCLI@2
            displayName: 'Run tests'
            inputs:
              command: 'test'
              projects: ${{ parameters.testProjectPath }}
              arguments: '-c Release'
              publishTestResults: true
              testRunTitle: 'Unit Tests'

          - task: DotNetCoreCLI@2
            displayName: 'Pack package'
            inputs:
              command: 'pack'
              packagesToPack: ${{ parameters.projectPath }}
              arguments: '-c Release'

          - task: DotNetCoreCLI@2
            displayName: 'Publish package to Azure Artifacts'
            inputs:
              command: 'push'
              publishVstsFeed: ${{ parameters.feedName }}