parameters:
  - name: appName
    default: ''
  - name: feedName
    default: ''
  - name: sonarName
    default: 'SonarQube'
  - name: jdkVersion
    default: '1.21'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: ${{ parameters.feedName }}
              mavenServiceConnections: ${{ parameters.feedName }}
            displayName: Maven Authenticate
          - task: SonarCloudPrepare@3
            inputs:
              SonarQube: SonarCloud
              scannerMode: 'cli'
              organization: 'piomin'
              projectKey: ${{ parameters.appName }}
              displayName: Analysis Preparation
              extraProperties: |
                sonar.qualitygate.wait=true
                sonar.scanner.scanOverDays=30
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: ${{ parameters.jdkVersion }}
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: true
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
            displayName: Maven Build
          - task: SonarCloudAnalyze@3
            inputs:
              timeoutSec: '300'
          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '300'
            displayName: Publish SonarQube Results
            condition: always()
          - task: CmdLine@2
            inputs:
              script: |
                VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                echo "##vso[task.setvariable variable=appVersion;isOutput=true]$VERSION"
                echo "##vso[build.updatebuildnumber]$VERSION"
                echo "Extracted version: $VERSION"
            name: SetVersion
            displayName: Set Version

