parameters:
  - name: appName
    default: ''
  - name: moduleName
    default: ''
  - name: feedName
    default: ''
  - name: projectPath
    default: '.'
  - name: sonarProjectKey
    default: ''
  - name: jdkVersion
    default: '1.21'
  - name: versionMode
    default: 'file'
  - name: skipChecks
    default: false
  - name: publish
    default: false

stages:
  - stage: Build
    displayName: 'Build/Publish'
    jobs:
      - job: Build_And_Publish
        steps:

          - checkout: appRepo
            persistCredentials: true
            fetchDepth: 0

#          - ${{ if eq(parameters.skipChecks, false) }}:
#            - task: Checkmarx AST@3
#              inputs:
#                CheckmarxService: 'Checkmarx'
#                projectName: ${{ parameters.moduleName }}
#                branchName: '$(Build.SourceBranchName)'
#                tenantName: 'frontex'

          - ${{ if eq(parameters.skipChecks, false) }}:
            - task: SonarCloudPrepare@3
              inputs:
                SonarQube: SonarCloud
                scannerMode: 'cli'
                configMode: 'manual'
                organization: 'piomin'
                cliProjectKey: ${{ parameters.sonarProjectKey }}
                displayName: Analysis Preparation
                extraProperties: |
                  sonar.verbose=true

          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: ${{ parameters.feedName }}
            displayName: Maven Authenticate
          - script: |
              echo "Injecting mirror for Azure Artifacts..."
              sed -i 's|<mirrors>|<mirrors><mirror><id>azure</id><mirrorOf>*</mirrorOf><url>https://pkgs.dev.azure.com/pminkows/_packaging/pminkows/maven/v1</url></mirror>|' ~/.m2/settings.xml
            displayName: 'Inject Maven mirror'
          - task: Maven@4
            inputs:
              mavenPomFile: '${{ parameters.projectPath }}/pom.xml'
              goals: 'clean package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: ${{ parameters.jdkVersion }}
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: true
              effectivePomSkip: false
              sonarQubeRunAnalysis: ${{ not(parameters.skipChecks) }}
            displayName: Maven Build

          - ${{ if eq(parameters.skipChecks, false) }}:
            - task: SonarCloudPublish@3
              inputs:
                pollingTimeoutSec: '300'
              displayName: Publish SonarQube Results
              condition: always()

          - ${{ if eq(parameters.versionMode, 'file') }}:
             - script: |
                 version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                 echo "##vso[task.setvariable variable=appVersion]$version"
                 echo "##vso[task.setvariable variable=imageTag;isOutput=true]$version"
                 echo "App version: $version"
               displayName: Get App Version
               name: SetVersion

          - ${{ if eq(parameters.versionMode, 'tag') }}:
             - task: gitversion-setup@4
               inputs:
                 versionSpec: '6.4.x'
                 displayName: Init git-version
             - task: gitversion-execute@4
               displayName: Get App Version
               name: GetVersion
             - script: |
                 git config user.email "buildagent@yourcompany.com"
                 git config user.name "Azure Pipelines"
                 version=$(GetVersion.MajorMinorPatch)
                 echo "##vso[task.setvariable variable=appVersion]$version"
                 echo "##vso[task.setvariable variable=imageTag;isOutput=true]$version"
                 echo "App version: $version"
                 git tag $version
                 git push origin $version
               displayName: Create Git Tag
               name: SetVersion

          - script: |
              if [ -f "${{ parameters.projectPath }}/Dockerfile" ]; then
                echo "##vso[task.setvariable variable=hasDockerfile]true"
                echo "##vso[task.setvariable variable=dockerfileExists;isOutput=true]true"
              else
                echo "##vso[task.setvariable variable=hasDockerfile]false"
                echo "##vso[task.setvariable variable=dockerfileExists;isOutput=true]false"
              fi
            displayName: "Check for Dockerfile"
            name: CheckDockerfile

          - script: |
              cd ${{ parameters.projectPath }}
              docker build -t quay.io/pminkows/${{ parameters.appName }}:$(appVersion) .
              docker images
            displayName: Build image
            condition: eq(variables.hasDockerfile, 'true')

          - script: |
              echo "Version:$(appVersion)"
              docker images
              docker login quay.io -u pminkows -p $(RedHatPassword)
              docker push quay.io/pminkows/${{ parameters.appName }}:$(appVersion)
            displayName: Push Image
            condition: eq(variables.hasDockerfile, 'true')

          - ${{ if eq(parameters.publish, true) }}:
            - task: Maven@4
              inputs:
                mavenPomFile: '${{ parameters.projectPath }}/pom.xml'
                goals: 'dependency:tree'
              displayName: Dependencies
            - task: Maven@4
              inputs:
                mavenPomFile: '${{ parameters.projectPath }}/pom.xml'
                goals: 'dependency:copy-dependencies'
                options: '-DoutputDirectory=$(Build.ArtifactStagingDirectory)/publish'
              displayName: Dependencies export
            - task: PublishBuildArtifacts@1
              inputs:
                pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
                artifactName: 'dependencies'
              displayName: Publish Maven dependencies