parameters:
  - name: appName
    default: ''
  - name: projectName
    default: ''
  - name: branchName
    default: 'main'

stages:
  - stage: ${{ parameters.appName }}_Sync
    displayName: 'Sync repos ${{ parameters.appName }}'
    jobs:
      - job: Sync
        steps:
          - checkout: git://${{ parameters.appName }}-config
            persistCredentials: true
            path: ${{ parameters.appName }}-local-config-repo

          - checkout: ${{ parameters.appName }}-config-repo
            path: ${{ parameters.appName }}-remote-config-repo

          - script: |
              cd ../${{ parameters.appName }}-remote-config-repo
              git status
#              git fetch origin
#              git reset --hard origin/${{ parameters.branchName }}
            displayName: "Update Azure Repos repo"
#
          - script: |
              cd ../${{ parameters.appName }}-local-config-repo
              git status
#              git fetch origin
#              git reset --hard origin/temppr || true
            displayName: "Update Azure Repos repo"

          - script: |
              pwd

              cd ../${{ parameters.appName }}-local-config-repo
              
              # Create new temporary branch
              BRANCH="temppr"
              git switch $BRANCH
              git status
              
              git config user.email "buildagent@azuredevops.com"
              git config user.name "Azure DevOps Pipeline"

              # Copy new files from GitHub repo
              rsync -av --exclude=".git" ../${{ parameters.appName }}-remote-config-repo/ .

              # Commit changes
              git add .
              git status
              git commit -m "Sync from GitHub repo $(date)" || echo "No changes to commit"

              # Push branch to Azure Repos
              git push origin $BRANCH
            displayName: Sync files

          - script: |
              ORG_URL="https://dev.azure.com/pminkows"
              PROJECT="${{ parameters.projectName }}"
              REPO="${{ parameters.appName }}-config"
              SOURCE_BRANCH="temppr"
              TARGET_BRANCH="${{ parameters.branchName }}"
              TITLE="Sync from GitHub repo"
              DESCRIPTION="Automated PR from GitHub -> Azure Repos"

              API_URL="$ORG_URL/$PROJECT/_apis/git/repositories/$REPO/pullrequests?api-version=7.1-preview.1"
              
              BODY=$(jq -n \
                --arg source "refs/heads/$SOURCE_BRANCH" \
                --arg target "refs/heads/$TARGET_BRANCH" \
                --arg title "$TITLE" \
                --arg desc "$DESCRIPTION" \
                '{sourceRefName:$source, targetRefName:$target, title:$title, description:$desc, reviewers: [{"id":"dc859b68-fc96-6b00-90f3-022ae0522e8a", "isRequired": true}]}')
              
              echo "$BODY"
              
              RESPONSE=$(curl -X POST \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $(System.AccessToken)" \
                  -d "$BODY" \
                  "$API_URL")
              
              PR_ID=$(echo "$RESPONSE" | jq -r '.pullRequestId')
              API_URL="$ORG_URL/$PROJECT/_apis/git/repositories/$REPO/pullrequests/$PR_ID?api-version=7.1-preview.1"
              
              curl -X PATCH \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $(System.AccessToken)" \
                  -d '{"completionOptions": {"deleteSourceBranch": false}, "autoCompleteSetBy": {"id": "663964c3-dd8e-4250-8b16-228895ea7834"}}' \
                  "$API_URL"
            env:
              System.AccessToken: $(System.AccessToken)
            displayName: "Create PR"