parameters:
  - name: moduleName
    default: ''
  - name: appName
    default: ''
  - name: projectPath
    default: '.'
  - name: sonarProjectKey
    default: ''
  - name: nodejsVersion
    default: '18.x'
  - name: build
    default: true
  - name: publish
    default: false
  - name: skipTests
    default: false
  - name: skipChecks
    default: false
  - name: versionMode
    default: 'file'

stages:
  - stage: Build
    displayName: 'Build/Publish'
    jobs:
      - job: Build_And_Publish
        steps:

          - checkout: appRepo
            persistCredentials: true
            fetchDepth: 0

          - task: DownloadSecureFile@1
            name: npmrc
            inputs:
              secureFile: 'npmrc'

          - task: NodeTool@0
            inputs:
              versionSpec: ${{ parameters.nodejsVersion }}
            displayName: Use Node.js ${{ parameters.nodejsVersion }}

          - script: |
              echo "Copying secure .npmrc to home directory"
              mkdir -p $HOME
              cp $(npmrc.secureFilePath) $HOME/.npmrc
            displayName: "Set up global .npmrc"

          - ${{ if eq(parameters.skipChecks, false) }}:
              - task: Checkmarx AST@3
                inputs:
                  CheckmarxService: 'Checkmarx'
                  projectName: ${{ parameters.moduleName }}
                  branchName: '$(Build.SourceBranchName)'
                  tenantName: 'frontex'

          # Install dependencies (production-only by default)
          - script: |
              cd ${{ parameters.projectPath }}
              npm ci --omit=dev
            displayName: Install dependencies

          - ${{ if eq(parameters.build, true) }}:
            - script: |
                cd ${{ parameters.projectPath }}
                npm run build
              displayName: 'Build'

          # Run tests
          - ${{ if eq(parameters.skipTests, false) }}:
            - script: |
                cd ${{ parameters.projectPath }}
                echo "Running tests..."
                npm test
              displayName: 'Test'

          - ${{ if eq(parameters.versionMode, 'file') }}:
            - script: |
                cd ${{ parameters.projectPath }}
                version=$(npm pkg get version | tr -d '"')
                echo "##vso[task.setvariable variable=appVersion]$version"
                echo "##vso[task.setvariable variable=imageTag;isOutput=true]$version"
                echo "App version: $version"
              displayName: Get App Version
              name: SetVersion

          - ${{ if eq(parameters.versionMode, 'tag') }}:
              - task: gitversion-setup@4
                inputs:
                  versionSpec: '6.4.x'
                  displayName: Init git-version
              - task: gitversion-execute@4
                displayName: Get App Version
                name: GetVersion
              - script: |
                  git config user.email "buildagent@yourcompany.com"
                  git config user.name "Azure Pipelines"
                  version=$(GetVersion.MajorMinorPatch)
                  echo "##vso[task.setvariable variable=appVersion]$version"
                  echo "##vso[task.setvariable variable=imageTag;isOutput=true]$version"
                  echo "App version: $version"
                  git tag $version
                  git push origin $version
                displayName: Create Git Tag
                name: SetVersion

          - ${{ if eq(parameters.skipChecks, false) }}:
            - task: SonarCloudPrepare@3
              inputs:
                SonarQube: SonarCloud
                scannerMode: 'cli'
                configMode: 'manual'
                organization: 'piomin'
                cliProjectKey: ${{ parameters.sonarProjectKey }}
                displayName: Analysis Preparation
                extraProperties: |
                  sonar.verbose=true
  #                sonar.projectBaseDir=$(Build.SourcesDirectory)/src/${{ parameters.moduleName }}
            - task: SonarCloudAnalyze@3
            - task: SonarCloudPublish@3
              inputs:
                pollingTimeoutSec: '300'
              displayName: Publish SonarQube Results
              condition: always()

          - script: |
              if [ -f "${{ parameters.projectPath }}/Dockerfile" ]; then
                echo "##vso[task.setvariable variable=hasDockerfile]true"
                echo "##vso[task.setvariable variable=dockerfileExists;isOutput=true]true"
              else
                echo "##vso[task.setvariable variable=hasDockerfile]false"
                echo "##vso[task.setvariable variable=dockerfileExists;isOutput=true]false"
              fi
            displayName: "Check for Dockerfile"
            name: CheckDockerfile

          - script: |
              cd ${{ parameters.projectPath }}
              docker build -t quay.io/pminkows/${{ parameters.appName }}:$(appVersion) .
              docker images
            displayName: Build image
            condition: eq(variables.hasDockerfile, 'true')

          - script: |
              echo "Version:$(appVersion)"
              docker images
              docker login quay.io -u pminkows -p $(RedHatPassword)
              docker push quay.io/pminkows/${{ parameters.appName }}:$(appVersion)
            displayName: Push Image
            condition: eq(variables.hasDockerfile, 'true')

#          - task: PublishBuildArtifacts@1
#            inputs:
#              PathtoPublish: '${{ parameters.projectPath }}'
#              ArtifactName: 'artifacts'
#              publishLocation: 'Container'
#            condition: eq(variables.hasDockerfile, 'true')